# Generated by Django 5.2.10 on 2026-02-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('birthday', 'Birthday'), ('graduation', 'Graduation'), ('generic', 'Generic')], max_length=50)),
                ('preview_image', models.ImageField(upload_to='template_previews/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='template_backgrounds/')),
                ('svg_overlay', models.FileField(blank=True, null=True, upload_to='template_svgs/')),
                ('default_primary_color', models.CharField(default='#7C3AED', max_length=50)),
                ('default_secondary_color', models.CharField(default='#F0E6FF', max_length=50)),
                ('default_font_family', models.CharField(default='PlayfairDisplay', max_length=100)),
                ('default_layout', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='event',
            name='accent_color',
            field=models.CharField(default='#852D63', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='body_font',
            field=models.CharField(default='PlayfairDisplay-Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='border_style',
            field=models.CharField(choices=[('simple', 'Simple Line'), ('rounded', 'Rounded Corners'), ('floral', 'Floral Pattern'), ('geometric', 'Geometric')], default='rounded', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='name_font',
            field=models.CharField(default='DancingScript-Bold', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_color',
            field=models.CharField(default='#7C3AED', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='secondary_color',
            field=models.CharField(default='#F0E6FF', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='show_border',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_decorations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='show_qr_background',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='template_choice',
            field=models.CharField(choices=[('modern', 'Modern Elegant'), ('classic', 'Classic Formal'), ('floral', 'Floral Design'), ('minimal', 'Minimalist'), ('custom', 'Custom Template')], default='modern', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='title_font',
            field=models.CharField(default='Marckscript-Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='guest',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='custom_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='svgoverlay',
            name='category',
            field=models.CharField(blank=True, choices=[('border', 'Border'), ('corner', 'Corner Design'), ('pattern', 'Pattern'), ('icon', 'Icon'), ('floral', 'Floral Design')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_color',
            field=models.CharField(default='#FDF4FF', max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof')], default='Mr', max_length=10),
        ),
    ]
